# write docker compose file for postgres database
version: '3.8'
services:
  postgres_db:
    image: postgres:13
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - 5432:5432
    volumes:
      - ./volume/postgres:/var/lib/postgresql/data
