version: '3.8'
services:
  db:
    container_name: postgres-db
    image: postgres:14
    restart: unless-stopped
    # env_file:
    #   - .env
    ports:
      - '5432:5432'
    volumes: 
      - db:/var/lib/postgresql/data

volumes:
  db:     